### ISSUE TITLE
Populate registry table with data

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-ckan-registry#72] opened 2019-01-07 03:40 UTC
Once #71 is complete use the CMS configuration and the JS API from #70 to populate the table with data from the appropriate resource.

This should include managing the pagination on the frontend too. Made through a static config

**Comment by NightJar** [comment] 2019-01-16 22:53
As per https://github.com/silverstripe/silverstripe-ckan-registry/issues/71#issuecomment-454974806 the PR for this issue will also add the table headers, as they come parts-in-parcel with the data.

**Comment by NightJar** [comment] 2019-01-18 02:18
@camfindlay We've run into an unexpected issue with this ... issue.

The "remove duplicates" option we've created in the CMS is not usable as expected.
The CKAN API gives reference to a [`distinct` modifier](https://docs.ckan.org/en/2.8/maintaining/datastore.html#ckanext.datastore.logic.action.datastore_search) to queries, which we had expected to be able to use akin to how it does in SQL.

However, in reality it seems to work counter-intuitively.
e.g. the [Family Services in Auckland](https://catalogue.data.govt.nz/dataset/family-services-directory/resource/496d2b91-2e9a-4e72-9c07-cf41141aefa6) set has 145 records.
Selecting "Provider Name", "Provider
Region", "Provider,
District" [sic] (the column names have line breaks in them) we get a whole bunch from the same Provider ID, meaning lots of duplicate rows.

Thought solution: Use the `distinct` option! :D
However, after using this we get...
145 results, including multiple groups of the same - Oh no! D:

Introducing ProviderID to the query shows that they are indeed all the same provider.


So we thought to introduce a search term: `Provider+Name=Kelly`
We get 3 results.
Using distinct, we get 1 results... but a total of 3!

This is ... unfortunate.
What should we do?

**Comment by NightJar** [comment] 2019-01-18 02:20
We thought to switch to the [CKAN SQL endpoint](https://docs.ckan.org/en/2.8/maintaining/datastore.html#ckanext.datastore.logic.action.datastore_search_sql) which seems to behave more expectly (being plain SQL).

This works great, until your SQL becomes more intense, and the Incapsula WAF blocks the request (which is interesting, select statements are fine until you introduce a subquery or method like `count(*)`!)

**Comment by ScopeyNZ** [comment] 2019-01-18 02:22
One issue is that the total doesn't account for any "DISTINCT" option - maybe that's a CKAN issue, or "working as intended"?

We can probably work around this by doing two queries when loading data but it's a bit kludgey.

**Comment by ScopeyNZ** [comment] 2019-01-18 03:41
Okay just to summarise:

#### Problems

- We cannot specify columns when we query distinct but we expect/allow for that in the CMS
- When we do query distinct the "total" record count in the response does not respect the distinct param. 
  - eg. We ask for all records where "Provider Name" matches "Kelly" with `distinct=1` - Result gives us one record, total indicates three records

#### Problem 1: Can't distinct on columns

This seems to be by design. I guess that was our mistake. I have a quote from me earlier saying that I can do it, but it does not seem possible now... There's a couple of solutions I can think of from the top of my head:
- We move the distinct option from "per column" to just be "per results". This actually might make it less confusing for users. This just means that there will never be two results in the table where all the columns are the same value. This should cover the real-life use case? Might be something to think about from a UX point of view (cc @sachajudd)
- We can run an additional CKAN request for each column marked as distinct and build a list of IDs that are "valid". Thinking about this - this might be really hard.

#### Problem 2: Distinct option doesn't give the right total

It's unclear if this is by design or not. Either way it means we can't show pagination correctly

----

We could solve this problem by delving into the `datastore_search_sql` endpoint, but the CKAN docs make this clear that it probably has limited support per CKAN instance. In our testing with data.govt.nz we've had Incapsula blocking some requests. We could probably solve this issue with some relatively complex SQL queries...:

```
SELECT count(*), "Provider Name" FROM (SELECT DISTINCT "ProviderID", "Provider Name" FROM "496d2b91-2e9a-4e72-9c07-cf41141aefa6" WHERE "Provider Name" ILIKE "Kelly") LIMIT 30
```

I'd prefer to avoid this though if possible - I think it reduces the compatibility with an arbitrary CKAN.

**Comment by camfindlay** [comment] 2019-01-19 19:34
Looks like the count issue is actually solved and awaiting a backport to the version we're current'y running... https://github.com/ckan/ckan/pull/4236

**Comment by ScopeyNZ** [comment] 2019-01-20 07:37
> Looks like the count issue is actually solved [ckan/ckan#4236](https://github.com/ckan/ckan/pull/4236) (we just need to apply the patch on our instance). In light of that... i'd say assume the count returns correct for Griddle display purposes...

Okay we can run with that. For pagination until that fix is applied the number of records in the result will not match the number specified and you might get duplicates between pages - but I guess that'll be fine.

The other option is that we are able to run a single count query in the first instance - this might be good as we can indicate we don't want a count for other queries: 

```
https://catalogue.data.govt.nz/api/3/action/datastore_search_sql?sql=SELECT count(DISTINCT "ProviderID") FROM "496d2b91-2e9a-4e72-9c07-cf41141aefa6"
```

> Distinct would need to be turned on at the dataset resource level ("[ ] This dataset contains duplicate rows for categories" or something) and as long as you don't also include those category columns in the results display that are also going to be used for a category based dropdown filter, you'll get a usable register search with expected results.

Yep I agree this is a good stop-gap that I also touched on:

> We move the distinct option from "per column" to just be "per results". This actually might make it less confusing for users. This just means that there will never be two results in the table where all the columns are the same value. This should cover the real-life use case? Might be something to think about from a UX point of view

I'll run it past Sacha on Tuesday. FWIW, I think if you end up raising anything against CKAN you should mention that the current behaviour is very mystifying. It seems to apply `DISTINCT` to all columns that you are "SELECTing" - not really very common behaviour. The only other idea here is that we could perform two API calls for each page - "SELECT" ProviderID with our filters with the "distinct" option on, then "SELECT again filtering on our previously requested ProviderIDs.

**Comment by ScopeyNZ** [comment] 2019-01-20 08:11
Doing a little code delving - it looks like the order of the columns _should_ matter and that you were on to something. I can't seem to generate a request that does what I expect it to do though:

https://github.com/ckan/ckan/blob/master/ckanext/datastore/backend/postgres.py#L1252-L1256

**Comment by ScopeyNZ** [comment] 2019-01-20 08:19
Never mind I'm getting confused - it does distinct on every column with that syntax. I'm thinking about the `DISTINCT ON (column)` syntax.

**Closed** 2019-01-22 21:17 UTC
Labels: affects/v4, change/minor, effort/easy, impact/high, type/enhancement, type/frontend
