### ISSUE TITLE
Search interface for keywords

### ISSUE THREAD

**Issue by rupachup** [silverstripe/silverstripe-ckan-registry#4] opened 2018-11-29 22:20 UTC
## User story
As a user looking for a record in a government directory
I want to be able to type in a keyword relating to the item I need to find
So that I can get the information I need and any related records to my search.

## Acceptance criteria

- [ ] The user knows what directory they are searching (it has a title)
- [ ] A short explanation can be provided with the search (it has a description/content)
- [ ] User is presented with a free text input for keywords
- [ ] When user types a keyword and clicks "Search" button (or presses enter) a set of results is displayed to them ordered by relevance to the search query.
- [ ] Results display in a grid with column headings.
- [ ] Results are paginated.
- [ ] User can further refine the results by changing the keyword or any filters.
- [ ] User can send the results URL to someone to see the same results based on their keywords and/or any filtered applied (filters in other user stories).
- [ ] The results can be styled to fit the rest of a websites brand/layout requirements (eg. can change from a grid to a more search result style results).
- [ ] We provide a default set of styles that fit the default CWP starter theme.
- [ ] There is a reference URL to get back to the source data on the CKAN instance being used.

### Notes

- The keyword box could be as simple as a text input filter auto added to the stack of filtered when you first add a "datasearch page"
- This is for the frontend design.

[Styleguide](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5c09c9d18e1f85001158544f)

To confirm whether we need to use React for this (cc @brynwhyman)

* Templates
* Accessible markup
* Customisable CSS classes
* Controller action to handle the filter form
* Filters are generated from CKANFilter models defined on the page (has_many) see https://github.com/silverstripe/silverstripe-ckan-registry/issues/5 and https://github.com/silverstripe/silverstripe-ckan-registry/issues/24

**Comment by robbieaverill** [comment] 2018-12-04 15:57
FYI I've raised #29 which might be a duplicate of this, but is more dev focussed.

**Comment by brynwhyman** [comment] 2018-12-10 03:51
No, we don't _need_ to use React for this frontend template. Given that the styleguide was based off the existing `silverstripe/silverstripe-registry` page template, we should utilise what CSS we can from that and, unless there's a good reason not to, just vanilla JS.

**Comment by ScopeyNZ** [comment] 2018-12-12 10:12
I've been a bit slack on keeping on top of issues. Although we don't _need_ to use React for this I think we definitely _should_. We need to populate the content of the table with a response from a CKAN API:

#### Option A - We use JavaScript to make the table
- Vanilla JS: when the team is so familiar with React seems like a backwards step. This is not a "simple" javascript component
- React JS: The team is very familiar with it and there's a working PoC with open source code that we can "borrow" from. The biggest issue is templating the data. Not quite sure how that'll work
- Something else?: Maybe there's an option we haven't considered but I think it'll be too much effort to get the team across it given our current time allowences

#### Option B: - Use PHP
- We can allow developers to template with SilverStripe template syntax. This would be most similar to registry
- CKAN API requests have to pass-through the SilverStripe site. This was intended to be avoided. It would mean that usage of the data page would become quite a bit slower. With this method there's a lot more load on the SilverStripe site and no less load on the CKAN API.

Anyway, maybe I'm too much of a proponent for a JS implementation here, but I think it makes sense if we can come up with a good solution for templating.

**Comment by robbieaverill** [comment] 2018-12-12 13:06
Yeah I guess it's more of a question of "do we want to add opinion into a frontend module" which we haven't done before with the exception of using jQuery.

On the other hand, SS templating with a jQuery AJAX request would be lightweight and easy to achieve without introducing opinion on the JS library.

We can make the frontend "templates" adjustable by making each component injectable with the JS injector, which also hasn't been done on the frontend yet but I assume it would work. Otherwise we'd provide decent BEM class names for theming.

It would be a step away from regular SS frontend development though, so if we do go with React we'd need to make sure it's for the right reasons

**Comment by ScopeyNZ** [comment] 2018-12-12 22:43
Perhaps @chillu would be interested in this discussion. Feel free to ping me on Slack or in person if you want more context around what we're discussing here.

**Comment by camfindlay** [comment] 2019-02-07 06:32
This can be closed.

**Closed** 2019-02-07 06:33 UTC
Labels: affects/v4, change/minor, type/enhancement
