### ISSUE TITLE
Filter interface to refine results returned

### ISSUE THREAD

**Issue by rupachup** [silverstripe/silverstripe-ckan-registry#5] opened 2018-11-29 22:21 UTC
## User story
As a website visitor, I want to be able to perform a filtered search on a registry, so I can find relevant information.

## Acceptance Criteria

- [ ] There is a space in the UI where a user can expect to apply one or more filters to their query.
- [ ] The layout of the space allows for adding 1 or more filter blocks or types.
- [ ] Filters have a common appearance or pattern (even if they perform different types of filtering (eg location, category etc.
- [ ] This story is more about setting the pattern and rules for how filters behave, there are individual stories for each filter type. 

### Notes

- Suggest using same template styles as registry module to get moving.
- We have decided to borrow from the Registry feature that already exists. Suggest revise and resize given this new variable.

**Comment by robbieaverill** [comment] 2018-12-04 16:00
Is this a duplicate of #4?

**Comment by NightJar** [comment] 2018-12-19 02:41
Seems like it.
Although the part of #4 that reads

>As a user looking for a record in a government directory

Makes me wonder if it's a different kind of search.
@camfindlay @brynwhyman ?

**Comment by camfindlay** [comment] 2018-12-19 07:36
This user story is for the frontend rather than the CMS.

**Comment by camfindlay** [comment] 2018-12-19 07:36
Read the user story ;)

**Comment by camfindlay** [comment] 2018-12-19 07:37
And it covers adding one or more filters other than the initial "search all the things" field that #4 hints at.

**Comment by NightJar** [comment] 2018-12-19 20:23
Ok neat, thanks for the elaboration/clarification :)

As a status update:
The "default filter" is set up on connecting to a resource as at #54 
As you mention there is no technical difference, so I think this covers that.

However there is still no front-end work for website visitors to consume, so I'll leave this open :)

**Comment by robbieaverill** [comment] 2018-12-20 09:41
>I think some of the labels I set in trello have been lost as you mention, I split out CMS side and frontend stories.

Note to self: go through Trello and add `type/frontend` GitHub labels to all frontend issues here

**Comment by camfindlay** [comment] 2019-02-07 06:33
Close this since we've already cleared in the trello board against ACs.

**Closed** 2019-02-07 06:34 UTC
Labels: affects/v4, change/minor, type/enhancement
